Added visualisation of tests results.

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -28,7 +28,7 @@ jobs:
       - name: Build
         run: dotnet build src/Yabbin.TimeSpent.sln --configuration Release --no-restore
       - name: Test
-        run: dotnet test src/Yabbin.TimeSpent.sln --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
+        run: dotnet test src/Yabbin.TimeSpent.sln --logger trx;LogFileName=test-results.trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
       - name: Upload dotnet test results
         uses: actions/upload-artifact@v2
         with:
@@ -36,3 +36,10 @@ jobs:
           path: TestResults-${{ matrix.dotnet-version }}
         # Use always() to always run this step to publish test results when there are test failures
         if: ${{ always() }}
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: XUnit                 # Name of the check run which will be created
+          path: "TestResults-${{ matrix.dotnet-version }}/test-results.trx"    # Path to test results
+          reporter: dotnet-trx        # Format of test results
